# Dockerfile
FROM python:3.10-slim

# Set the working directory
WORKDIR /usr/src/app

# Copy the Python script to the working directory
COPY temp/script.py . 

# Command to run the script
CMD ["python3", "script.py"]